[tool.poetry]
name = "jargon-lang"
version = "0.7.0"
description = "A simple programming language."
authors = ["user1344-gh"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
